#!/bin/bash
clear
database="/root/usuarios.db"
fun_drop () {
	_portaD=$(ps x | grep dropbear | grep -v grep | awk -F'-p ' '{print $2}' | sed 's/ .*//g' | uniq)
	_log='/var/log/auth.log'
	_loginS='Password auth succeeded'
	for _pid in `ps ax |grep dropbear |grep  "$_portaD" |awk '{print $1}'`; do
		for _pidLog in `grep $_pid $_log |grep "$_loginS" |awk -F" " '{print $3}'`; do
			_login=`grep $_pid $_log |grep "$_pidLog" |grep "$_loginS"`
			_user=`echo $_login |awk -F" " '{print $10}' | sed -r "s/'/ /g"`
			echo -e "$_user" "$_pid"
		done
	done
}
if [ ! -f "$database" ]
then
	echo "Arquivo usuarios.db nao encontrado"
	exit 1
fi
while : ; do
	clear
	echo -e "\E[42;1;37m               LIMITER USUARIOS                 \E[0m"
    echo -e "\E[42;1;37m Ususario                             status.   \E[0m"
    while read usline
    do
		user="$(echo $usline | cut -d' ' -f1)"
		limit="$(echo $usline | cut -d' ' -f2)"
		conssh="$(ps -u $user | grep sshd | wc -l)"
		if netstat -nltp|grep 'dropbear'> /dev/null;then
            condrop="$(fun_drop | grep -E "$user" | wc -l)"
		    piddrop="$(fun_drop | grep -E "$user" | tail -1 | awk '{print $ NF}')"
        else
            condrop=0
            piddrop=0
        fi
        cnx=$(($condrop + $conssh))
		if [[ $cnx -gt 0 ]]; then
		tput setaf 3 ; tput bold ; printf '  %-33s%s\n' $user verificando; tput sgr0
		if netstat -nltp|grep 'dropbear' > /dev/null; then
		    if [[ $condrop -gt $limit ]]; then
		       echo -e "\E[41;1;37m Usuario desconectado por ultrapassar o limite! \E[0m"
		       kill -9 $piddrop
		    fi
		fi
		if [[ $conssh -gt $limit ]]; then
		    pidkill=$(($conssh - $limit))
		    echo -e "\E[41;1;37m Usuario desconectado por ultrapassar o limite! \E[0m"
		    for pidssh in `(ps -u $user |grep sshd| head -n $pidkill |awk '{print $1}')`; do
		        kill -9 $pidssh
		    done
		fi
		fi
     done < "$database"
     sleep 10
donefi