#!/bin/bash
#Install Manager Repositorio Movido
#Ruta https://github.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/tree/master/Install/Sistema

rm $HOME/Plus && rm $HOME/Plus.1 && rm $HOME/Plus.2 > /dev/null 2>&1

apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/Sistema/Plus; chmod 777 Plus; ./Plus
