#!/bin/bash
clear
echo -e "\E[44;1;37m           PANEL SSHPLUS v15           \E[0m"
echo ""
echo -e "                \033[1;31mATTENTION"
echo ""
echo -e "\033[1;32mALWAYS REPORT THE SAME PASSWORD"
echo -e "\033[1;32mALWAYS COMPLETE QUESTIONS WITH\033[1;37m Y"
echo ""
echo -e "\033[1;36mSTARTING INSTALLATION"
echo ""
echo -e "\033[1;33mWAIT..."
apt-get update > /dev/null 2>&1
echo ""
echo -e "\033[1;36mINSTALLING THE APACHE2\033[0m"
echo ""
echo -e "\033[1;33mWAIT..."
apt-get install apache2 -y > /dev/null 2>&1
apt-get install cron curl unzip -y > /dev/null 2>&1
echo ""
echo -e "\033[1;36mINSTALLING DEPENDENCIES\033[0m"
echo ""
echo -e "\033[1;33mWAIT..."
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y > /dev/null 2>&1
service apache2 restart 
echo ""
echo -e "\033[1;36mINSTALLING MySQL\033[0m"
echo ""
sleep 1
apt-get install mysql-server -y 
echo ""
clear
echo -e "                \033[1;31mATTENTION"
echo ""
echo -e "\033[1;32mALWAYS REPORT THE SAME PASSWORD WHEN ASKING"
echo -e "\033[1;32mALWAYS COMPLETE QUESTIONS WITH\033[1;37m Y"
echo ""
echo -ne "\033[1;33mEnter, To Proceed!\033[1;37m"; read
mysql_install_db
mysql_secure_installation
clear
echo -e "\033[1;36mINSTALLING PHPMYADMIN\033[0m"
echo ""
echo -e "\033[1;31mATTENTION \033[1;33m!!!"
echo ""
echo -e "\033[1;32mSELECT OPTION \033[1;31mAPACHE2 \033[1;32mWITH THE KEY '\033[1;33mSPACE\033[1;32m'"
echo ""
echo -e "\033[1;32mSelect \033[1;31mYES\033[1;32m IN THE OPTION TO FOLLOW (\033[1;36mdbconfig-common\033[1;32m)"
echo -e "TO CONFIGURE THE DATABASE"
echo ""
echo -e "\033[1;32mREMEMBER THE SAME PASSWORD WHEN REQUESTED"
echo ""
echo -ne "\033[1;33mEnter, To Proceed!\033[1;37m"; read
apt-get install phpmyadmin -y
php5enmod mcrypt
service apache2 restart
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y > /dev/null 2>&1
if [ "$(php -m |grep ssh2)" = "ssh2" ]; then
  true
else
  clear
  echo -e "\033[1;31mCRITICAL ERROR\033[0m"
  rm $HOME/install.sh
  exit
fi
apt-get install php5-curl > /dev/null 2>&1
service apache2 restart
clear
echo ""
echo -e "\033[1;31mATTENTION \033[1;33m!!!"
echo ""
echo -ne "\033[1;32mEnter the same password\033[1;37m: "; read senha
echo -e "\033[1;32mOK\033[1;37m"
sleep 1
mysql -h localhost -u root -p$senha -e "CREATE DATABASE sshplus"
clear
echo -e "\033[1;36mFINISHING INSTALLATION\033[0m"
echo ""
echo -e "\033[1;33mWAIT..."
echo ""
cd /var/www/html
wget https://www.dropbox.com/s/6ne5wfrk5gvnjsa/SSHPLUSV15.zip > /dev/null 2>&1
sleep 1
unzip SSHPLUSV15.zip > /dev/null 2>&1
rm -rf SSHPLUSV15.zip index.html > /dev/null 2>&1
service apache2 restart
sleep 1
if [[ -e "/var/www/html/pages/system/pass.php" ]]; then
sed -i "s;suasenha;$senha;g" /var/www/html/pages/system/pass.php > /dev/null 2>&1
fi
sleep 1
cd
mv /var/www/html/sshplus.sql /root/sshplus.sql > /dev/null 2>&1
sleep 1
if [[ -e "$HOME/sshplus.sql" ]]; then
    mysql -h localhost -u root -p$senha --default_character_set utf8 sshplus < sshplus.sql
    rm /root/sshplus.sql
else
    clear
    echo -e "\033[1;31mERROR WHILE IMPORTING DATABASE\033[0m"
    sleep 2
    rm /root/install.sh > /dev/null 2>&1
    exit
fi
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.ssh.php ' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.sms.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.online.ssh.php' >> /etc/crontab
echo '10 * * * * root /usr/bin/php /var/www/html/pages/system/cron.servidor.php' >> /etc/crontab
/etc/init.d/cron reload > /dev/null 2>&1
/etc/init.d/cron restart > /dev/null 2>&1
chmod 777 /var/www/html/admin/pages/servidor/ovpn
chmod 777 /var/www/html/admin/pages/download
chmod 777 /var/www/html/admin/pages/faturas/comprovantes
service apache2 restart
sleep 1
clear
echo -e "\033[1;32mSuccessfully Installed Panel!"
echo ""
echo -e "\033[1;36mYOUR PANEL\033[1;37m $IP/admin\033[0m"
echo -e "\033[1;36mUSERNAME\033[1;37m admin\033[0m"
echo -e "\033[1;36mPASSWORD\033[1;37m admin\033[0m"
echo ""
echo -e "\033[1;33mChange password when logging in to panel\033[0m"
cat /dev/null > ~/.bash_history && history -c
rm /root/install.sh > /dev/null 2>&1
