#!/bin/bash
clear
#——————————————————
# CRIADOR POR @CRAZY_VPN
# VERSAO 1.0
# SLOW DNS TUNNEL
#——————————————————

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CORTITLE='\033[1;41m'
SCOLOR='\033[0m'
banner='
 ___ _    _____      _____  _  _ ___ 
/ __| |  / _ \ \    / /   \| \| / __|
\__ \ |_| (_) \ \/\/ /| |) | .  \__ \
|___/____\___/ \_/\_/ |___/|_|\_|___/'

echo -e "${CORTITLE}=====================================${SCOLOR}" 
echo -e "${CORTITLE}       SSHPLUS CLIENTE SLOWDNS       ${SCOLOR}"
echo -e "${CORTITLE}=====================================${SCOLOR}" 
echo -e "${RED}$banner${SCOLOR}"
[[ ! -e dns ]] && {
    yes| termux-setup-storage > /dev/null 2>&1
    unset LD_PRELOAD > /dev/null 2>&1
    cd $HOME
    mv slowdns $PREFIX/bin/slowdns
    chmod +x $PREFIX/bin/slowdns
    [[ $(grep -c 'slowdns' $PREFIX/etc/profile) == '0' ]] && echo 'slowdns' >> $PREFIX/etc/profile
    echo -e "\n${GREEN}BAIXANDO O SCRIPT POR FAVOR AGUARDE ! ${SCOLOR}"
    curl -O https://sshplus.net/scripts/dns > /dev/null 2>&1
    echo -e "\n${RED}[${YELLOW}!${RED}] ${YELLOW}SCRIPT BAIXADO ! DA PROXIMA VEZ\nEXECULTE APENAS O COMANDO ${RED}(${GREEN}slowdns${RED})\n${YELLOW}MESMO QUE VOCÊ ESTEJA OFFLINE !${SCOLOR}"
    chmod +x dns
}
[[ ! -e $HOME/credenciais ]] && {
    ns=$1
    [[ -z "$ns" ]] && {
        echo -e "\n${RED}COMANDO IMCOMPLETO${SCOLOR}"
        exit 0
    }
    chave=$2
    [[ -z "$chave" ]] && {
        echo -e "\n${RED}COMANDO IMCOMPLETO${SCOLOR}"
        exit 0
    }
    echo -e "$ns\n$chave" > $HOME/credenciais
} || {
    perg=$(echo "${SCOLOR}[s/n]: ")
    echo -e "\n${YELLOW}O SCRIPT JA ESTÁ CONFIGURADO COM UM\nSEEVIDOR E ESTA PRONTO PARA CONEXAO"
    read -p "$(echo -e "${GREEN}QUER CONTINUAR COM O MESMO?${SCOLOR} [s/n]: ")" -e -i s opc
    [[ "$opc" != @(s|sim|S|SIM) ]] && {
        rm $HOME/credenciais dns > /dev/null 2>&1
        rm $PREFIX/bin/slowdns > /dev/null 2>&1
        sed -i '/slowdns/d' $PREFIX/etc/profile > /dev/null 2>&1
        echo -e "\n${RED}SCRIPT REMOVIDO !${SCOLOR}"
        rm slowdns > /dev/null 2>&1
        exit 0
    } || {
        unset LD_PRELOAD > /dev/null 2>&1
        ns=$(sed -n 1p $HOME/credenciais)
        chave=$(sed -n 2p $HOME/credenciais)
    }
}
echo -ne "\n${RED}[${YELLOW}!${RED}] ${YELLOW}PARA CONTINUAR CERTIFIQUE-SE DE\nESTÁ APENAS COM OS ${RED}(${YELLOW}DADOS MOVEIS${RED})\n${YELLOW}ATIVADO ${GREEN}ENTER ${YELLOW}PARA CONTINUAR.. ${SCOLOR}"; read
$HOME/dns -udp 208.67.222.222:53 -pubkey ${chave} ${ns} 127.0.0.1:2222 > /dev/null 2>&1 &
echo -e "\n${RED}[${GREEN}√${RED}]${SCOLOR} - ${GREEN}SLOWDNS INICIADO!${SCOLOR} - ${RED}[${GREEN}√${RED}]\n\n${RED}[${YELLOW}!${RED}] ${YELLOW}AGORA CONECTE-SE EM UM APP VPN\nOU CLICK EM ${GREEN}ENTER ${RED}PARA DESCONECTAR ${SCOLOR}"; read
piddns=$(ps x| grep -w 'dns' | grep -v 'grep'| awk -F' ' {'print $1'})
[[ ${piddns} != '' ]] && kill ${piddns} > /dev/null 2>&1