#!/bin/bash

fun_ip () {
MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
[[ "$MEU_IP" != "$MEU_IP2" ]] && echo "$MEU_IP2" || echo "$MEU_IP"
}
IP="$(fun_ip)"

colocar_arquivo_online() {
  local i=1
  local select_arc=()

  echo -e "\n\033[1;32mARQUIVOS/DIRETÓRIOS NO HOME\033[0m\n"
  for my_arqs in "$HOME"/*; do
    arq=$(basename "$my_arqs")
    select_arc[$i]="$arq"
    if [[ -d "$my_arqs" ]]; then
      tipo="Dir"
    else
      tipo="File"
    fi
    echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m• \033[1;37m$tipo \033[1;32m$arq"
    ((i++))
  done

  ((i--))
  [[ $i -eq 0 ]] && echo -e "\033[1;31mNenhum arquivo ou diretório disponível!\033[0m" && return

  echo -ne "\n\033[1;36mSelecione o número do item para colocar online: \033[0m"
  read -r slct

  local arquivo_move="${select_arc[$slct]}"
  [[ -z "$arquivo_move" || ! -e "$HOME/$arquivo_move" ]] && echo -e "\033[1;31mOpção inválida!\033[0m" && return

  mkdir -p /var/www/html
  [[ ! -e /var/www/html/index.html ]] && touch /var/www/html/index.html

  # Copia arquivos ou diretórios
  if [[ -d "$HOME/$arquivo_move" ]]; then
    cp -r "$HOME/$arquivo_move" /var/www/html/
  else
    cp "$HOME/$arquivo_move" /var/www/html/
  fi

  chmod -R 755 /var/www/html

  echo -e "\n\033[1;32mLink: \033[1;36mhttp://$IP:80/$arquivo_move\033[0m"
  echo -e "\033[1;32mItem colocado online com sucesso!\033[0m"
}


remover_arquivo_online() {
  local i=1
  local select_arc=()

  echo -e "\n\033[1;32mARQUIVOS/DIRETÓRIOS ONLINE\033[0m\n"
  for my_arqs in /var/www/html/*; do
    arq=$(basename "$my_arqs")
    # Quitamos el filtro de index.html/php y directorios
    select_arc[$i]="$arq"
    if [[ -d "$my_arqs" ]]; then
      tipo="Dir"
    else
      tipo="File"
    fi
    echo -e "\033[1;31m[\033[1;36m$i\033[1;31m] \033[1;37m• \033[1;37m$tipo \033[1;32m$arq - \033[1;36mhttp://$IP:80/$arq\033[0m"
    ((i++))
  done

  ((i--))
  [[ $i -eq 0 ]] && echo -e "\033[1;31mNenhum arquivo ou diretório online encontrado!\033[0m" && return

  echo -ne "\n\033[1;36mInforme o número para remover: \033[0m"
  read -r slct

  local arquivo_move="${select_arc[$slct]}"
  [[ -z "$arquivo_move" ]] && echo -e "\033[1;31mOpção inválida!\033[0m" && return

  rm -rf "/var/www/html/$arquivo_move"
  echo -e "\033[1;32m'$arquivo_move' removido com sucesso!\033[0m"
}


ver_arquivos_online() {
  echo -e "\n\033[1;32mLINKS ONLINE \033[0m\n"
  for my_arqs in /var/www/html/*; do
    arq=$(basename "$my_arqs")
    if [[ -d "$my_arqs" ]]; then
      tipo="Dir"
    else
      tipo="File"
    fi
    echo -e "\033[1;37m$tipo \033[1;32m[$arq] \033[1;36mhttp://$IP:80/$arq\033[0m"
  done
}

# Función de menú principal
menu_arquivos_online() {

while true; do

  clear
  echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo -e "\033[1;32m GERENCIAR ARQUIVO ONLINE \033[0m"
  echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo ""
  echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mCOLOCAR ARQUIVO ONLINE"
  echo -e "\033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mREMOVER ARQUIVO ONLINE"
  echo -e "\033[1;31m[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mVER LINKS DOS ARQUIVOS ONLINE"
  echo -e "\033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSalir \033[1;32m<\033[1;33m<\033[1;31m<"
  echo ""
  echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo ""
  echo -ne "\033[1;32m¿QUÉ DESEA HACER \033[1;33m?\033[1;31m?\033[1;37m : "; read x

case "$x" in
   1 | 01)
   colocar_arquivo_online
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   2 | 02)
   remover_arquivo_online
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   3 | 03)
   ver_arquivos_online
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   0 | 00)
   echo -e "\033[1;31mSalindo...\033[0m"
   sleep 1
   clear
   exit;
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 1
esac
done
}

# Executar menu
menu_arquivos_online
