#!/bin/bash
echo "$ipdovps" >/etc/IP
rm -rf /bin/criarusuario /bin/remover /bin/alterarlimite /bin/alterarsenha /bin/mudardata /bin/expcleaner /bin/droplimiter /bin/addhost /bin/listar /bin/sshmonitor /bin/ajuda /bin/menu /bin/blockt /bin/userbackup /bin/tcpspeed /bin/badvpn /bin/otimizar /bin/speedtest /bin/banner /bin/limite /bin/limiter /bin/infousers /bin/senharoot /bin/reiniciarservicos /bin/reiniciarsistema /bin/attscript /bin/criarteste /bin/socks /bin/conexao /bin/infousers /bin/botssh /bin/delscript /bin/versao > /dev/null 2>&1
rm -rf /etc/SSHPlus/bot /etc/SSHPlus/ShellBot.sh /etc/SSHPlus/cabecalho /etc/SSHPlus/proxy.py > /dev/null 2>&1
sed -i '/127.0.0.1 portalrecarga.vivo.com.br/d' /etc/hosts
sed -i '/127.0.0.1 d1n212ccp6ldpw.cloudfront.net/d' /etc/hosts
sed -i '/127.0.0.1 www.portalsva2.vivo.com.br/captive-static/tarif-def/pd/index.html/d' /etc/hosts
sed -i '/127.0.0.1 www.portalsva2.vivo.com.br/captive-static/tarif-def/cd/index.html/d' /etc/hosts
if [ -d /etc/SSHPlus ]
then
echo ""
else
mkdir /etc/SSHPlus
fi
if [ -d /etc/SSHPlus/senha ]
then
echo ""
else
mkdir /etc/SSHPlus/senha
fi
if ps x | grep "bot_plus"|grep -v grep 1>/dev/null 2>/dev/null; then
	pidbot_plus=$(ps x|grep "bot_plus"|awk -F "pts" {'print $1'})
    kill -9 $pidbot_plus > /dev/null 2>&1
    screen -wipe > /dev/null 2>&1
fi
if [[ -e /etc/squid3/squid.conf ]]; then
wget $_lnk/_script_$/squid1.txt -O /tmp/sqd1 1>/dev/null 2>/dev/null
echo "acl url3 dstdomain -i $ipdovps" > /tmp/sqd2
wget $_lnk/_script_$/squid2.txt -O /tmp/sqd3 1>/dev/null 2>/dev/null
cat /tmp/sqd1 /tmp/sqd2 /tmp/sqd3 > /etc/squid3/squid.conf
wget $_lnk/_script_$/payload.txt -O /etc/squid3/payload.txt 1>/dev/null 2>/dev/null
echo " " >> /etc/squid3/payload.txt
elif [[ -e /etc/squid/squid.conf ]]; then
wget $_lnk/_script_$/squid1.txt -O /tmp/sqd1 1>/dev/null 2>/dev/null
echo "acl url3 dstdomain -i $ipdovps" > /tmp/sqd2
wget $_lnk/_script_$/squid.txt -O /tmp/sqd3 1>/dev/null 2>/dev/null
cat /tmp/sqd1 /tmp/sqd2 /tmp/sqd3 > /etc/squid/squid.conf
wget $_lnk/_script_$/payload.txt -O /etc/squid/payload.txt 1>/dev/null 2>/dev/null
echo " " >> /etc/squid/payload.txt
fi
ptvp=$(sed -n '1 p' /etc/openvpn/server.conf | awk '{print $NF}')
if [[ "$ptvp" == "443" ]]; then
echo ""
else
grep -v "^Port 443" /etc/ssh/sshd_config > /tmp/ssh && mv /tmp/ssh /etc/ssh/sshd_config
echo "Port 443" >> /etc/ssh/sshd_config
fi
grep -v "^PasswordAuthentication yes" /etc/ssh/sshd_config > /tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
wget $_lnk/_script_$/diversos/addhost.sh -O /bin/addhost > /dev/null 2>&1
chmod +x /bin/addhost
wget $_lnk/_script_$/diversos/alterarsenha.sh -O /bin/alterarsenha > /dev/null 2>&1
chmod +x /bin/alterarsenha
wget $_lnk/_script_$/diversos/criarusuario2.sh -O /bin/criarusuario > /dev/null 2>&1
chmod +x /bin/criarusuario
wget $_lnk/_script_$/diversos/delhost.sh -O /bin/delhost > /dev/null 2>&1
chmod +x /bin/delhost
wget $_lnk/_script_$/diversos/expcleaner2.sh -O /bin/expcleaner > /dev/null 2>&1
chmod +x /bin/expcleaner
wget $_lnk/_script_$/diversos/mudardata.sh -O /bin/mudardata > /dev/null 2>&1
chmod +x /bin/mudardata
wget $_lnk/_script_$/diversos/criarteste.sh -O /bin/criarteste > /dev/null 2>&1
chmod +x /bin/criarteste
wget $_lnk/_script_$/diversos/remover.sh -O /bin/remover > /dev/null 2>&1
chmod +x /bin/remover
wget $_lnk/_script_$/diversos/droplimiter.sh -O /bin/droplimiter > /dev/null 2>&1
chmod +x /bin/droplimiter
wget $_lnk/_script_$/diversos/alterarlimite.sh -O /bin/alterarlimite > /dev/null 2>&1
chmod +x /bin/alterarlimite
wget $_lnk/_script_$/diversos/ajuda.sh -O /bin/ajuda > /dev/null 2>&1
chmod +x /bin/ajuda
wget $_lnk/_script_$/diversos/sshmonitor2.sh -O /bin/sshmonitor > /dev/null 2>&1
chmod +x /bin/sshmonitor
wget $_lnk/_script_$/diversos/badvpn.sh -O /bin/badvpn > /dev/null 2>&1
chmod +x /bin/badvpn
wget $_lnk/_script_$/diversos/tcpspeed.sh -O /bin/tcpspeed > /dev/null 2>&1
chmod +x /bin/tcpspeed
wget $_lnk/_script_$/diversos/userbackup.sh -O /bin/userbackup > /dev/null 2>&1
chmod +x /bin/userbackup
wget $_lnk/_script_$/diversos/blockt.sh -O /bin/blockt > /dev/null 2>&1
chmod +x /bin/blockt
wget $_lnk/_script_$/diversos/otimizar.sh -O /bin/otimizar > /dev/null 2>&1
chmod +x /bin/otimizar
wget $_lnk/_script_$/diversos/menu.sh -O /bin/menu > /dev/null 2>&1
chmod +x /bin/menu
wget $_lnk/_script_$/diversos/speedtest.sh -O /bin/speedtest > /dev/null 2>&1
chmod +x /bin/speedtest
wget $_lnk/_script_$/diversos/banner.sh -O /bin/banner > /dev/null 2>&1
chmod +x /bin/banner
wget $_lnk/_script_$/diversos/senha.sh -O /bin/senharoot > /dev/null 2>&1
chmod +x /bin/senharoot
wget $_lnk/_script_$/diversos/Rservicos.sh -O /bin/reiniciarservicos > /dev/null 2>&1
chmod +x /bin/reiniciarservicos
wget $_lnk/_script_$/diversos/Rsistema.sh -O /bin/reiniciarsistema 1>/dev/null 2>/dev/null
chmod +x /bin/reiniciarsistema
wget $_lnk/_script_$/diversos/attscript.sh -O /bin/attscript > /dev/null 2>&1
chmod +x /bin/attscript
wget $_lnk/_script_$/diversos/conexao.sh -O /bin/conexao > /dev/null 2>&1
chmod +x /bin/conexao
wget $_lnk/_script_$/diversos/detalhes.sh -O /bin/detalhes > /dev/null 2>&1
chmod +x /bin/detalhes
wget $_lnk/_script_$/diversos/delscript.sh -O /bin/delscript > /dev/null 2>&1
chmod +x /bin/delscript
wget $_lnk/_script_$/diversos/botssh.sh -O /bin/botssh > /dev/null 2>&1
chmod +x /bin/botssh
wget $_lnk/_script_$/diversos/infousers.sh -O /bin/infousers > /dev/null 2>&1
chmod +x /bin/infousers
wget $_lnk/_script_$/diversos/limiter.sh -O /bin/limiter > /dev/null 2>&1
chmod +x /bin/limiter
wget $_lnk/_script_$/diversos/cabecalho.sh -O /etc/SSHPlus/cabecalho > /dev/null 2>&1
chmod +x /etc/SSHPlus/cabecalho
wget $_lnk/_script_$/diversos/bot -O /etc/SSHPlus/bot > /dev/null 2>&1
chmod +x /etc/SSHPlus/bot
wget $_lnk/_script_$/diversos/proxy.py -O /etc/SSHPlus/proxy.py > /dev/null 2>&1
chmod +x /etc/SSHPlus/proxy.py
sed -i '3i\127.0.0.1 portalrecarga.vivo.com.br/recarga\' /etc/hosts
sleep 1
sed -i '4i\127.0.0.1 d1n212ccp6ldpw.cloudfront.net\' /etc/hosts
sleep 1
sed -i '5i\127.0.0.1 www.portalsva2.vivo.com.br/captive-static/tarif-def/pd/index.html\' /etc/hosts
sleep 1
sed -i '6i\127.0.0.1 navegue.vivo.com.br/pre/\' /etc/hosts
sleep 1
sed -i '7i\127.0.0.1 navegue.vivo.com.br/controle/\' /etc/hosts
service ssh restart
wget -qO- $_lnk/_script_$/diversos/confirme.py > /home/confirme.py
python /home/confirme.py "$name" "$ipdovps"
rm -rf /home/confirme.py 1>/dev/null 2>&1
wget -qO- ssh-plus.tk/script/versao | sed -n '1 p' > /bin/versao
service apache2 restart
service ssh restart > /dev/null 2>&1
if [[ -e /etc/squid/squid.conf ]]; then
squid -k reconfigure > /dev/null 2>&1
service squid restart > /dev/null 2>&1
elif [[ -e /etc/squid3/squid.conf ]]; then
squid3 -k reconfigure > /dev/null 2>&1
service squid3 restart > /dev/null 2>&1
fi
wget $_lnk/_script_$/1/kira -O /home/kira > /dev/null 2>&1
