#!/bin/bash
clear
cor[0]="\033[0m"
cor[1]="\033[0;34m"
cor[2]="\033[1;32m"
cor[3]="\033[1;37m"
cor[4]="\033[1;36m"
cor[5]="\033[1;33m"
cor[6]="\033[1;35m"

txt[126]="Esse Script Foi Projetado"
txt[127]="Para Melhorar A Latencia"
txt[128]="e Velocidade Do Servidor!"
txt[129]="Analizando"
txt[130]="Este é um script experimental"
txt[131]="Use por sua conta e risco!"
txt[132]="Este script irá alterar algumas"
txt[133]="configurações de rede"
txt[134]="do sistema para reduzir"
txt[135]="a latência e melhorar a velocidade"
txt[136]="Prosseguir Com A Instalação?"
txt[137]="As configurações de rede"
txt[138]="foram adicionadas com sucesso"
txt[139]="já foram adicionadas no sistema!"
txt[140]="Deseja remover as configurações"
txt[141]="As configurações de rede"
txt[142]="foram removidas com sucesso"

fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;32mINICIANDO O TCPSPEED... \033[0m\n"
tcp_speed () {
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[4]} ${txt[126]}"
echo -e "${cor[4]} ${txt[127]}"
echo -e "${cor[4]} ${txt[128]}"
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[5]} ${txt[129]}"
sleep 1s
if [[ `grep -c "^#ADM" /etc/sysctl.conf` -eq 0 ]]; then
#INSTALA
echo -e "${cor[5]} ${txt[130]}"
echo -e "${cor[5]} ${txt[131]}"
echo -e "${cor[5]} ${txt[132]}"
echo -e "${cor[5]} ${txt[133]}"
echo -e "${cor[5]} ${txt[134]}"
echo -e "${cor[5]} ${txt[135]}"
echo -e "${cor[1]} =================================== ${cor[0]}"
read -p " ${txt[136]} [s/n]: " -e -i s resp_osta
echo -e "\033[1;37m"
if [[ "$resp_osta" = 's' ]]; then
unset resp_osta
echo "#ADM" >> /etc/sysctl.conf
echo "net.ipv4.tcp_window_scaling = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_slow_start_after_idle = 0" >> /etc/sysctl.conf
sysctl -p /etc/sysctl.conf > /dev/null 2>&1
echo -e "${cor[5]} ${txt[137]} TCP"
echo -e "${cor[5]} ${txt[138]}"
echo -e "${cor[1]} =================================== ${cor[0]}"
return
 else
echo -e "${cor[1]} =================================== ${cor[0]}"
return
fi
 else
#REMOVE
echo -e "${cor[5]} ${txt[137]} TCP"
echo -e "${cor[5]} ${txt[139]}"
echo -e "${cor[1]} =================================== ${cor[0]}"
read -p " ${txt[140]} TCP? [s/n]: " -e -i n res_posta
if [[ "$res_posta" = 's' ]]; then
unset res_posta
grep -v "^#ADM
net.ipv4.tcp_window_scaling = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_slow_start_after_idle = 0" /etc/sysctl.conf > /tmp/syscl && mv -f /tmp/syscl /etc/sysctl.conf
sysctl -p /etc/sysctl.conf > /dev/null 2>&1
echo -e "${cor[5]} ${txt[141]} TCP"
echo -e "${cor[5]} ${txt[142]}"
echo -e "${cor[1]} =================================== ${cor[0]}"
return
 else
echo -e "${cor[1]} =================================== ${cor[0]}"
return
 fi
fi
}
tcp_speed